// Pre-seeded project ideas for when Supabase is not configured
export const PROJECT_IDEAS = [
  { id: '1', emoji: '🌱', title: 'Plant Dating App', description: 'Swipe right if your fern is compatible with their succulent! A dating app for houseplants.' },
  { id: '2', emoji: '🪨', title: 'Rock Rental', description: 'Rent premium rocks by the day. Browse, add to cart, checkout. E-commerce for the truly patient.' },
  { id: '3', emoji: '📋', title: 'Meeting Bingo', description: 'Bingo card for useless meeting moments: "Someone says synergy", "Camera off", "Can you hear me?"' },
  { id: '4', emoji: '🔥', title: 'Code Roaster', description: 'Paste your code and get roasted. "Oh, you call THAT a function?"' },
  { id: '5', emoji: '💪', title: 'Drill Sergeant Meditation', description: 'Guided meditation narrated by a drill sergeant. "BREATHE! I SAID BREATHE CALMLY!"' },
  { id: '6', emoji: '🍲', title: 'Q Foods Delivery', description: 'Food delivery but only foods that start with the letter Q. Quinoa for everyone!' },
  { id: '7', emoji: '🕊️', title: 'Pigeon Conspiracy Feed', description: 'A social network exclusively for conspiracy theories about pigeons being government drones.' },
  { id: '8', emoji: '🎵', title: 'Kazoo Jukebox', description: 'Spotify but every song is a kazoo cover. Experience Bohemian Rhapsody like never before.' },
  { id: '9', emoji: '☁️', title: 'Angry Cloud Storage', description: 'Cloud storage that yells at you when you upload files. "ANOTHER SCREENSHOT?!"' },
  { id: '10', emoji: '⏰', title: 'Procrastination Tracker', description: 'Tracks how long you spend tracking your productivity instead of being productive.' },
  { id: '11', emoji: '🤥', title: 'Excuse Generator', description: 'AI-powered excuse generator for missing meetings. "My WiFi was attacked by digital squirrels."' },
  { id: '12', emoji: '📅', title: 'Guilt-Trip Calendar', description: 'A calendar that passive-aggressively guilt-trips you about missed appointments.' },
  { id: '13', emoji: '🔄', title: 'Reverse Social', description: 'A social network where you can only post on other people\'s profiles—about yourself.' },
  { id: '14', emoji: '💍', title: 'Weather Mood Ring', description: 'The weather is based on your mood, not the actual forecast. Sad? It\'s raining.' },
  { id: '15', emoji: '⚔️', title: 'Compliment Duel', description: 'A competitive battle where players fight using only sincere compliments.' },
  { id: '16', emoji: '⏪', title: 'Retro Task Manager', description: 'A todo app that looks and feels like Windows 95. Add tasks, nostalgia.' },
  { id: '17', emoji: '🦆', title: 'Rubber Duck Debugger', description: 'An AI rubber duck for debugging that quacks back unhelpful advice.' },
  { id: '18', emoji: '🎉', title: 'Introvert Party Planner', description: 'Plans parties where nobody shows up. Finally, the perfect event!' },
  { id: '19', emoji: '↩️', title: 'Opposite Day', description: 'Everything in the app does the opposite of what you expect. Chaos guaranteed.' },
  { id: '20', emoji: '📌', title: 'Mundane NFT Gallery', description: 'Mint NFTs of your most boring possessions. Own the blockchain rights to a paperclip!' },
]
